from __future__ import annotations

import subprocess
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]


def test_base_image_uses_the_hash_locked_runtime_dependencies() -> None:
    dockerfile = (REPOSITORY_ROOT / "Dockerfile").read_text(encoding="utf-8")
    base = _dockerfile_stages(dockerfile)["base"]

    assert "COPY pyproject.toml README.md uv.lock ./" in base
    assert "COPY requirements/runtime.lock /tmp/runtime.lock" in base
    assert "python -m pip install --require-hashes -r /tmp/runtime.lock" in base
    assert "pip install --upgrade pip" not in base
    assert "pip install -e ." not in base
    assert 'import pandas_market_calendars; import thericher_v2' in base


def test_runtime_lock_is_the_current_uv_export() -> None:
    expected = (REPOSITORY_ROOT / "requirements" / "runtime.lock").read_text(encoding="utf-8")
    result = subprocess.run(
        [
            "uv",
            "export",
            "--locked",
            "--no-dev",
            "--no-editable",
            "--no-emit-project",
            "--format",
            "requirements.txt",
        ],
        check=True,
        cwd=REPOSITORY_ROOT,
        capture_output=True,
        text=True,
    )

    generated_command = (
        "#    uv export --locked --no-dev --no-editable --no-emit-project "
        "--format requirements.txt --output-file requirements/runtime.lock\n"
    )
    assert expected.startswith("# This file was autogenerated by uv via the following command:\n")
    assert generated_command in expected
    assert result.stdout == expected.replace(" --output-file requirements/runtime.lock", "", 1)


def _dockerfile_stages(dockerfile: str) -> dict[str, str]:
    stages: dict[str, str] = {}
    current_name: str | None = None
    current_lines: list[str] = []
    for line in dockerfile.splitlines():
        lower = line.lower()
        if lower.startswith("from "):
            if current_name is not None:
                stages[current_name] = "\n".join(current_lines)
            current_lines = [line]
            current_name = lower.rsplit(" as ", maxsplit=1)[-1].strip()
        elif current_name is not None:
            current_lines.append(line)
    if current_name is not None:
        stages[current_name] = "\n".join(current_lines)
    return stages
